version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    
  backend:
    build: ./backend
    container_name: server_container
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URL=mongodb://mongo:27017/fullProjectDB

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "5173:5173"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development

volumes:
  mongo_data: