services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    
  server:
    build: .
    container_name: server_container
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/userDB

volumes:
  mongo_data: